name: Auto Update Schedule

on:
  schedule:
    - cron: '*/30 * * * *' # Запуск кожні 30 хвилин
  workflow_dispatch:      # Кнопка для ручного запуску

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests beautifulsoup4 cloudscraper
        
      - name: Run parser
        run: python parser.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name "SvitloBot"
          git config --global user.email "bot@github.com"
          git add schedule.json
          git commit -m "Auto-update schedule: $(date)" || exit 0
          git push
